import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "aboutㅇㅇㅇ",
  description: "Generated by about",
};

const AboutLayout = ({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) => {
  return (
    <>
      {children}
      {modal} {/* about/@modal만 처리 */}
    </>
  );
};

export default AboutLayout;
