import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "docs",
  description: "Generated by docs",
};

const DocsLayout = ({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) => {
  return (
    <>
      {children}
      {modal} {/* docs/@modal만 처리 */}
    </>
  );
};

export default DocsLayout;
